name: Test with PyTest and Other Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: ${{github.ref_name}}

jobs:
  PyTest:
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.filter.outputs.built }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run pytest

      - name: If Success in above steps
        id: filter
        run: |
          echo "built=true" >> $GITHUB_OUTPUT


      # - name: Write Output
      #   run: echo true > depends_PyTest.txt

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: depends_PyTest
      #     path: depends_PyTest.txt

  Dummy:
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.filter.outputs.built }}
    steps:

    - uses: actions/checkout@v4
      
    - name: Yo
      shell: bash
      run: |
        curl ipinfo.io

    - name: If Success in above steps
      id: filter
      run: |
        echo "built=true" >> $GITHUB_OUTPUT

    # - name: Write Output
    #   run: echo true > depends_Dummy.txt

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: depends_Dummy
    #     path: depends_Dummy.txt

  SecurityCheck:
    runs-on: ubuntu-latest

    needs:
    - PyTest
    - Dummy

    if: |
      needs.PyTest.outputs.built == 'true' ||
      needs.Dummy.outputs.built == 'true'

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Install Requirements
      run: |
        pip install bandit

    - name: Check Security
      run: |
        make securityCheck